#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace QPTags
{
	namespace QPAbilites
	{
		QIPAWORLDUEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
		QIPAWORLDUEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseBuff);
	}
	namespace QPCue
	{
		QIPAWORLDUEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UseFood);
		QIPAWORLDUEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Poisoning);
	}

}